import { Outfit } from 'next/font/google'
import './globals.css'

import Header from '@/components/ui/comps/Header'
import Footer from '@/components/ui/comps/Footer'

import { ThemeProvider } from '@/components/ui/comps/ThemeProvider'

const outfit = Outfit ({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ThemeProvider attribute='class' defaultTheme='light'> 
        <Header />
        {children}
        <Footer />
        </ThemeProvider>
        </body>
    </html>
  )
}
